/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pawparadise1;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


/**
 *
 * @author Alejandro
 */
public class Registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        ImageIcon fondo = new ImageIcon(getClass().getResource("FondoAnimales.jpg.jpeg"));
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JtextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Jraza = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JHisotria = new javax.swing.JTextField();
        Jesterilizado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Jvacunas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Jedad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Jtiempo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jsexo1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        btnSubirFoto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawparadise1/Foto1.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawparadise1/Imagen6.png"))); // NOI18N
        getContentPane().add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 120));

        Titulo.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        Titulo.setText("REGISTRO");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, 40));

        jLabel1.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel1.setText("Cuentanos un poco de su historia y cómo conociste a este peludito:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel2.setText("Nombre del Peludito:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        getContentPane().add(JtextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 400, 40));

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel3.setText("Raza (si la sabes) :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        getContentPane().add(Jraza, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 400, 40));

        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel4.setText("Edad o un aproximado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        getContentPane().add(JHisotria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 580, 80));

        Jesterilizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No sé" }));
        Jesterilizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JesterilizadoActionPerformed(evt);
            }
        });
        getContentPane().add(Jesterilizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 770, 400, 40));

        jLabel5.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel5.setText("Se encuentra esterilizado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, -1, -1));
        getContentPane().add(Jvacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 590, 40));

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        Jedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JedadActionPerformed(evt);
            }
        });
        getContentPane().add(Jedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 400, 40));

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel7.setText("Hace cuanto tiempo esta contigo y motivo del porque quieres darlo en adopción: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));
        getContentPane().add(Jtiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 590, 40));

        jLabel8.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel8.setText("Sube una foto de tu peludito:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 820, -1, -1));

        Jsexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        Jsexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jsexo1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jsexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 400, 40));

        jLabel9.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel9.setText("Ingresa el nombre de las vacunas que tiene:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        lblFoto.setText("      Adjunta la foto del peludito aquí");
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 860, 220, 220));

        btnSubirFoto.setText("Subir Foto");
        btnSubirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubirFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1090, -1, -1));

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JedadActionPerformed

    private void JesterilizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JesterilizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JesterilizadoActionPerformed

    private void Jsexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jsexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jsexo1ActionPerformed

    private void btnSubirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirFotoActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    int resultado = fileChooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {
        File archivoSeleccionado = fileChooser.getSelectedFile();
        ImageIcon imagen = new ImageIcon(archivoSeleccionado.getAbsolutePath());

        // Escalar imagen al tamaño del JLabel
        Image imagenEscalada = imagen.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH);
        lblFoto.setIcon(new ImageIcon(imagenEscalada));
            }        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubirFotoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
   
    }//GEN-LAST:event_jButton1ActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField JHisotria;
    private javax.swing.JTextField Jedad;
    private javax.swing.JComboBox<String> Jesterilizado;
    private javax.swing.JTextField Jraza;
    private javax.swing.JComboBox<String> Jsexo1;
    private javax.swing.JTextField JtextField;
    private javax.swing.JTextField Jtiempo;
    private javax.swing.JTextField Jvacunas;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnSubirFoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFoto;
    // End of variables declaration//GEN-END:variables
}
